### ISSUE TITLE
Add a configurable Oauth2 provider

### ISSUE THREAD

**Issue by axel-rutz** [zorn-v/nextcloud-social-login#1]
This looks awesome!

The used hybridauth library brings ready made plugins for the industry giants. Additional providers need to be coded, [which is quite simple](https://hybridauth.github.io/developer-ref-extend-hybridauth.html) (3 urls + 1 scope).
Now let's suppose we want to add a custom provider, but either can't code or don't have access to the server (managed service). What would help is a parametrizable provider where the site admin fills their info (3 urls + 1 scope).

**Comment by zorn-v** [comment]
Scope always can be "emai" I think. And there not only urls should be configured. Providers return info as they want - identifier may be `uid` or `user_id` or something else for examle. Same for photoURL.

**Comment by axel-rutz** [comment]
This would really be helpful. We have a small association here and it would be a huge win if we can provide central authorization via the drupal openid_connect server module.
(Implementing this is also likely to give the app some traction as i'm sure we are not the only ones.)
I'm quite busy but can volunteer some manual testig for that.

**Comment by zorn-v** [comment]
In last version you can add any openid provider

**Comment by Treyone** [comment]
Thanks for adding that, it's really nice !
I tried to use it with our internal openid provider but got stuck with `No OpenID Server found at https://XXX`, no matther what I tried. I explored the source code and discovered that it was because my provider ([dex](https://github.com/coreos/dex)) does not have  `<link rel="openid.server" href="...">` (here: https://github.com/zorn-v/nextcloud-social-login/blob/ac5fc74303690c02aadd135db5ea0a39e138f558/3rdparty/hybridauth/hybridauth/src/Thirdparty/OpenID/LightOpenID.php#L713), and does not have a xrds document.

Is there a way to enhance that ?
- either make the endpoints configurable manually in the config page
- use the openid standard [discovery mechanism](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest)
- Add an open to allow OAuth2, not only OpenID. On that, configuring authorize URL, token URL and scopes may be sufficient.

**Comment by zorn-v** [comment]
Adding configurable fields is quite boring and brings potential bugs. Maybe later.

**Comment by Treyone** [comment]
No problem, I'm forking and I will propose a PR when I'm done.

**Comment by zorn-v** [comment]
Ok, But test it well and don't break current functionality )
Attach someting like TravisCI (and write auto tests) is overkill I think...

**Comment by Treyone** [comment]
Here it is ! https://github.com/zorn-v/nextcloud-social-login/pull/6
Hope it's OK with you.
A CI and automated testing would be nice, but I guess it's out of scope here indeed.

**Comment by zorn-v** [comment]
First of all, I'd made this app for myself. http://admin.inter-cat.ru/ 
Other things was obvious and I implemented them too. 
Research"dex" (how it response etc.) is over my desires

**Comment by zorn-v** [comment]
Released in v1.4.0
