### ISSUE TITLE
Configurable "preferred usename" claim

### ISSUE THREAD

**Issue by rysiekpl** [zorn-v/nextcloud-social-login#122]
Social Login seems to be using the `sub` claim for creating the username in Nextcloud, combining it with the provider name. As a result, usernames such as `internal-provider-name-3a67d4b7-4e53-4920-bcb5-3981c1c1fe9c` are created.

It would be great to be able to configure the claim used for username creation, just like a group claim can be configured to get the groups. For example, Keycloak provides a `preferred_username` claim, which would be the right thing to use in this case.

**Comment by zorn-v** [comment]
`sub` is for user id. Display name taken from other claims. In nexctcloud if display name is empty, uid used instead.

BTW  I added `preferred_username` as one of that claims when testing keycloak. Seems forgot to commit :smile: 

Check v2.1.2

**Comment by seblu** [comment]
Hello,

I'm testing social-login v2.2.3 as OIDC authenticator against an on premise gitlab instance. 

Gitlab has no `preferred_username` (https://docs.gitlab.com/ee/integration/openid_connect_provider.html), so currently, the login is `<internal-provider-name>-<gitlab-numeric-id>`.
Ideally, as suggested in this bug report, if we could define the field to use, the gitlab `username` claim would be best.

It looks like the current username pattern make login of already existing users fails because the email exists and the username is not the same. Am I correct?

**Comment by zorn-v** [comment]
> It looks like the current username pattern make login of already existing users fails because the email exists and the username is not the same. Am I correct?

No, already existing users must explicitly assign external accounts to their. Appropriate setting must be enabled for allowing this.
Connecting can be done in "Social login" section of user settings

**Comment by seblu** [comment]
ok. Is there a setting to make this association happen when a user log in with it's social account?

I mean, as `username` would not match the one they have on the Gitlab instance, I cannot enable user creation with social-login and I'll need to manually create accounts in nextcloud with the same `username`.
With the current association user experience, I will need to generate and distribute a local password and ask them to follow a procedure to make them associate with Gitlab. Not friendly and straightforward that we can expect to a regular SSO by clicking on the Gitlab button. Not to mention confusion created by messages like `mail already exists`.

**Comment by zorn-v** [comment]
> Is there a setting to make this association happen when a user log in with it's social account?

No. And will not be due security reasons.
Imagine two configured providers e.g. github and gitlab and there are two different users with same username there

> Not to mention confusion created by messages like mail already exists

I do not understand about what it

**Comment by seblu** [comment]
> No. And will not be due security reasons.
> Imagine two configured providers e.g. github and gitlab and there are two different users with same username there

I see your point. This type of matching requires a strong trust between nextcloud user base and the provider user base, which is not something we can assume with regular social network authenticators.

I realize that I'm maybe trying to bend social-login to act as an _OpenID Connect_ backend with a **trusted** gitlab user database (as the initial reporter with keycloak).  The objective was to use `social-login` app like  the `SSO & SAML authentication` app or `LDAP user and group backend` app and
it's maybe beyond the scope you want. As it's working so good as OIDC authenticator, it was tempting. :smile:

**Comment by zorn-v** [comment]
If you have trusted gitlab user db, why you just not enable "auto create user" setting ?

**Comment by seblu** [comment]
As usernames will not match the trusted database, already existing users and new users will not have the same id (`foo` vs `internal-foo`). This will be error prone and confusing in the long term. For example:
- new users who latter add a local password (in case of failure of the SSO), will have to remember their login is different between gitlab and nextcloud ;
- if we latter add a LDAP (or SAML) backend, userid will not match.

As database username matching is not trusted, already existing users will face to an error message  (about their email already exists) when they will use the trusted authentication. This is not the same behavior on our other tools (e.g: rocketchat) using the trusted SSO.

**Comment by zorn-v** [comment]
> This is not the same behavior on our other tools

Try to register user in gitlab with email registered in github and then try to "log in" via github with registered user with that email.

![image](https://user-images.githubusercontent.com/12619075/67506517-85cdd380-f6d0-11e9-913f-924d51630bf5.png)

Well, rocketchat have security issues I think :wink:

**Comment by seblu** [comment]
I do not think we can say that, it's a basic central authentication setup, like what we can achieve with the [LDAP module](https://docs.nextcloud.com/server/17/admin_manual/configuration_user/user_auth_ldap.html#expert-settings).
When Rocketchat is configured to delegate its authentication to a third party authority (e.g. our private Gitlab), we can allow it to (optionally) «merge users», which link local users account with the auth one.

If I understand your example correctly, we have two user accounts with the same email in 2 databases (a public github, a private gitlab). In the configuration I was referring to, the rocketchat only rely on the private gitlab auth. So, the public github account, must be linked **securely** with the private gitlab account, whatever the email they have respectively.

Even if we imagine that both a private gitlab and public github auth are done on rocketchat/nextcloud+social-login, we could have :
- an user database which has authority on local users, matching them based on a **trusted** field and with the ability to relink users or creating new one.
- a social/public authentication (i.e gitlab.com, github.com, google, etc) **without** the ability to relink or create new users and where association cannot be done based on a field match.

With the example you provided, the login with github will behave exactly like now (either refused because email already exists, either create a new users prefixed with <internal-provider>)

**Comment by 1bigchonk** [comment]
New pull request #168 should fix @rysiekpl's issue. 

Could be changed to username, and a custom mapper for keycloak could be used, and that would fix @seblu's issue.

**Comment by C0rn3j** [comment]
For those that want to hack around this meanwhile, you can toss out the `internalname-` part out by commenting it like so here:

https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Service/ProviderService.php#L325

```
//        $uid = $provider.'-'.$profileId;
        $uid = $profileId;
        if (strlen($uid) > 64 || !preg_match('#^[a-z0-9_.@-]+$#i', $profileId)) {
//            $uid = $provider.'-'.md5($profileId);
            $uid = md5($profileId);
        }
//        return $this->login($uid, $profile, $provider.'-');
        return $this->login($uid, $profile, '');
    }
```

And I also wanted to use the user email instead of keycloak ID, so that's a single change here:

https://github.com/zorn-v/nextcloud-social-login/blob/master/lib/Provider/CustomOpenIDConnect.php#L35
```
//        $userProfile->identifier  = $data->get('sub');
        $userProfile->identifier  = $data->get('email');
```

Before and after:
![image](https://user-images.githubusercontent.com/1641362/87018256-4a792380-c1d1-11ea-8336-f22d404c8b37.png)

**Comment by C0rn3j** [comment]
Is this a wontfix then?
Will we have to hack around the plugin on each release if we don't want to have a `keycloak-UUID`-like usernames?

**Comment by zorn-v** [comment]
It is not a bug and nothing to fix. 
I already say many times - UID is not username, and users must not change it in any way. 
You can use another app like https://apps.nextcloud.com/apps/oidc_login if you wish.

**Comment by C0rn3j** [comment]
>It is not a bug 
It is pretty much a missing feature.

I am migrating from LDAP to Keycloak, and currently our users have LDAP UUIDs.

Meaning that when I try to login via this plugin, a NEW user gets created with the keycloak-[keycloak-uuid] username, instead of allowing me to just configure it to use the LDAP UUID via a mapper.

>already existing users must explicitly assign external accounts to their

I want this done seamlessly, just like other SSO integrations like Gitlab or Redmine do it, I don't follow why I should be using a fork when this could be a setting for setups like mine?

**Comment by seblu** [comment]
> I already say many times - UID is not username, and users must not change it in any way.
We don't request users to change their username, we request a way to make administrators configure the mapping key to not create extra user names.

**Comment by zorn-v** [comment]
> could have a warning

Which nobody read usually

> but that is not the case for us

And does not matter how many users can have problems with this "feature" in future ?

> make administrators configure the mapping key

And what happens if admin configure changeable by user field ?

BTW, you can create "mapping" via `*PREFIX*sociallogin_connect` table. It will also work with disabled "allow_login_connect" option

**Comment by C0rn3j** [comment]
>Which nobody read usually

I understand your concern, but this limits people with a legitimate use case.
As it stands I changed the source code, which is far from ideal.

>And does not matter how many users can have problems with this "feature" in future ?

People will not have problems with the value being changeable if they do not change it.
Admins breaking their setup because they ignore a warning and misconfigure the plugin should not be your worry.

**Comment by zorn-v** [comment]
> Admins breaking their setup because they ignore a warning and misconfigure the plugin should not be your worry.

I do not want that my app become a "security issue" when admin just misconfigured something, because he jus did not know what he does - just follow "some instruction"
Like public mongodb/elasticsearch without passwords etc...

**Comment by bminer** [comment]
Duplicate of #66
