### ISSUE TITLE
Custom Oauth2 with Nextcloud Provider

### ISSUE THREAD

**Issue by christianwohlgemuth** [zorn-v/nextcloud-social-login#170]
Hello,

i'm trying to link two next cloud instances with oauth.
During login i get the error "Provider API returned an unexpected response".

The following configuration is present:

nextcloud.example.com => oauth2 provider
home.example.com => oauth2 client

**Nextcloud OAuth 2.0 clients configuration**
_nextcloud.example.com => adminstration => security => OAuth 2.0 clients_
Name: home.example.com
Redirection URI: http://home.example.com/index.php/apps/sociallogin/custom_oauth2/home.example.com
Client Identifier: <a lot of characters>
Secret: <even more characters>

**Social Login configuration**
_home.example.com = Administration => Social Login => Custom Oauth2_
Internal name: home.example.com
Title: home.example.com
API Base URL: https://nextcloud.example.com
Authorize url: https://nextcloud.example.com/index.php/apps/oauth2/authorize
Token url: https://nextcloud.example.com/index.php/apps/oauth2/api/v1/token
Profile url: https://nextcloud.example.com/ocs/v2.php/cloud/user?format=json
Logout URL: <empty>
Client Id: <a lot of characters>
Client Secret: <even more characters>
Scope: <empty>
Profile Fields: <empty>
Groups claim: <empty>
Button style: None
Default group: None

in both instances there is no entry in the logs (with loglevel 0)

**Comment by chrros95** [comment]
The problem is in the response structure of the profile URL. Nextcloud return the profil data in the path _ocs -> data_ but sociallogin tries to find the data in the same level as "ocs".

As a result the identifier isn't found which leads to the error.
A quick and dirty solution, would be to insert `$data = new Data\Collection($data->get("ocs")->data);` right below
`$data = new Data\Collection($response);` in the file _lib/Provider/CustomOAuth2.php_
Another more versatile approach is my commit [d9aca91](https://github.com/chrros95/nextcloud-social-login/commit/d9aca915bb74fd222ffdf35b7259664f9ec7b314)

**Comment by chrros95** [comment]
@zorn-v If prepared a final commit in my feature branch [attribute-path](https://github.com/chrros95/nextcloud-social-login/tree/attribute-mapping).
Is it a pull request worth?

**Comment by zorn-v** [comment]
I think better handle "ocs->profile" in hardcode then allow users to change it
