### ISSUE TITLE
Nextcloud 21 Support

### ISSUE THREAD

**Issue by jaddie** [zorn-v/nextcloud-social-login#238]
Hi,

I am just wondering if this supports Nextcloud & PHP 7.4 fully as I am having some errors in the log related to PHP foreach as well as the login not seeming to work even though the app is all setup and such for Facebook Login.

I am a bit confused what I am possibly doing wrong so wanted to ask first before I dig any further.

Cheers

**Comment by zorn-v** [comment]
Which errors do you have in log ?

**Comment by martinkoutecky** [comment]
I don't know if this is the same issue, but could be. I only set up social login after upgrade to NC21, so I don't know if what broke it was the upgrade or something else. I'm trying to authenticate against mailcow (custom OAuth2). The login correctly takes me to mailcow, I log in there, confirm I want to give permissions, and then nextcloud gives the following error:

`Signed API request has returned an error. HTTP error 404. Raw Provider API response: <html> <head><title>404 Not Found</title></head> <body> <center><h1>404 Not Found</h1></center> <hr><center>nginx</center> </body> </html> .`

In the NC log I get something like this

`session_start(): Ignoring session_start() because a session is already active at /path/to/NC/lib/private/Session/Internal.php#207`

... which looks like https://github.com/nextcloud/server/issues/25807 ... so I'm not sure it's related to the social login not working?

I can provide more logs if you can be specific in what would be helpful. Thanks!

**Comment by zorn-v** [comment]
Any other confirmations of NC 21 users that something does not work ?

**Comment by martinkoutecky** [comment]
@zorn-v sorry -- I found out the error was caused by some typos in the configuration, so I've got it working and the issue was not related to NC21.
