### ISSUE TITLE
Could this be modified to work with Azure B2C?

### ISSUE THREAD

**Issue by Jason9973** [zorn-v/nextcloud-social-login#315]
Hello Everyone,

So we have been working with the Azure B2C OpenID Implementation.  SO as usual, MS does their own thing on standards.  Anyways long story short, B2C standard flow is not exposing the Standard EMAIL Attribute.  Instead it is exposing a String Collection called EMAILS...  So normally in other applications I am calling EMAILS.0 which in our case is the desired value..  Is there a way in a future version of this App you could expose this attribute as a setting?

Thanks,
Jason

**Comment by zorn-v** [comment]
I did not understand anything. Can you show raw example of requests/responses ? With cleared sensitive data of course.

**Comment by Jason9973** [comment]
Hello,

I have attached a standard Response Token decoded from JWT.ms..  You can see the EMAILS attribute.

![image](https://user-images.githubusercontent.com/29556205/144053522-de75e785-98b6-4f54-8eeb-78bf61d334e3.png)

**Comment by zorn-v** [comment]
Same. Did not understand. How emails (it may changed) from some service can be identifiers as users ?

**Comment by Blackclaws** [comment]
I think the problem is the following:

By default if you want to use an email as the username you just use the email claim in the OIDC response (which should be a string).

In this case MS does not populate the email claim but instead creates a claim "emails" that is an array of string. 

The question is whether it is possible to add a selector function that takes the token from OIDC and projects the username out of it. In this case the function would be "emails[0]".

**Comment by Jason9973** [comment]
Blackclaws - That is precisely the issue and how I am working around it today.

**Comment by Jason9973** [comment]
In WordPress World..  Here is an example OAuth Plugin where I can do this selection just as an idea..

![image](https://user-images.githubusercontent.com/29556205/158575535-f1ab7828-50a9-4cc9-bdd5-31be73dffb4c.png)

**Comment by Jason9973** [comment]
This is great.  In which build will this be available? Thanks!
