### ISSUE TITLE
Programmatically adding group mappings to Custom OpenID Connect

### ISSUE THREAD

**Issue by PatrickTOToole** [zorn-v/nextcloud-social-login#441]
I was wondering if it is possible to update the group mappings via an api call. It seems that currently there is a POST request to <host>/apps/sociallogin/settings/save-admin but it requires a cookie and access token. I was wondering if there were any webDav or restful apis to edit these mappings.

**Comment by zorn-v** [comment]
Actually there is api for setting config values
https://github.com/zorn-v/nextcloud-social-login/blob/fbf73827a7223f1441ea19ab89220ab9568d5475/lib/Controller/ApiController.php#L29

In your case it should be like
`curl -d'key=custom_providers&config=YOUR_JSON_GOES_HERE' http://login:password@nc.domain/apps/sociallogin/api/config`

Config keys and values you can check in `oc_appconfig` table with `appid = 'sociallogin'`

**Comment by PatrickTOToole** [comment]
Oh that's great thank you. Just looked into it. Another related question, has the plugin been tested with a high number of groups? (potentially in the hundreds)

**Comment by PatrickTOToole** [comment]
And is there an api to retrieve the config?

**Comment by zorn-v** [comment]
> has the plugin been tested with a high number of groups? (potentially in the hundreds)

I don't know. It is related to nextcloud I think.

> And is there an api to retrieve the config?

Not yet

**Comment by PatrickTOToole** [comment]
Ok, thank you for your responsiveness and help. Closing the ticket

**Comment by zorn-v** [comment]
In 6.1.0 I added get config api method. Like this
```
curl -u'admin:password' http://localhost:1234/index.php/apps/sociallogin/api/config?key=custom_providers
```

**Comment by zorn-v** [comment]
Looks good, but there is only array and bool values in this app. Also instead of "magic numbers" there is constants in `OCP\IAppConfig`
And your numbers is wrong 😉 
```
	/** @since 29.0.0 */
	public const VALUE_SENSITIVE = 1;
	/** @since 29.0.0 */
	public const VALUE_MIXED = 2;
	/** @since 29.0.0 */
	public const VALUE_STRING = 4;
	/** @since 29.0.0 */
	public const VALUE_INT = 8;
	/** @since 29.0.0 */
	public const VALUE_FLOAT = 16;
	/** @since 29.0.0 */
	public const VALUE_BOOL = 32;
	/** @since 29.0.0 */
	public const VALUE_ARRAY = 64;
```

**Comment by moonkracker** [comment]
Oh, I tried to find where to find the mapping of these numbers and took values from the database and the table `oc_appconfig`, most likely there are values left from some old version of the plugin, but where I looked exactly `65` on `custom_provider`, and about the string values I just think that since there are values in the database, you can get them, it stores the version of plugin, whether the plugin is enabled and other information that is unlikely to be used, but if we can get it, than we can try to add this in getter func 

<img width="826" height="531" alt="Image" src="https://github.com/user-attachments/assets/f2aa697b-09e6-435d-bd4c-d9f8e194851d" />

Firstly I written the version like you did and then juz tried to get it more generic to parse every value that we have in db and also add `hasKey` method which can help avoid getting wrong values

**Comment by zorn-v** [comment]
It is bitmask (64 | 1) as array values is sensitive here. In `getValueType` it "unchecked" before return result
https://github.com/nextcloud/server/blob/10ef3a56d7620f35af15d22376d4388eca34818c/lib/private/AppConfig.php#L569

Strange solution - separate field with sensitive mark will be better IMHO, but as is.

Other "mixed" config values is nextcloud internal, so not need to consider they

**Comment by moonkracker** [comment]
Cool, thanks for great clarification. So will wait until social login plugin will be available for update. Thank you for your work
