### ISSUE TITLE
need support to drupal oauth2 server

### ISSUE THREAD

**Issue by sealionking** [zorn-v/nextcloud-social-login#68]
https://www.drupal.org/project/oauth2_server

I tried to setup it with custom openid connect,  but got errors

Signed API request has returned an error. HTTP error 403. Raw Provider API response: {"error":"insufficient_scope","error_description":"The request requires higher privileges than provided by the access token"}.

the endpoints are like

https://exmample.com/oauth2/authorize
https://exmample.com/oauth2/token
https://exmample.com/oauth2/userinfo

which are the default for open connect supplied by the module oauth2 server.

I can login to another drupal instance with drupal's openid connect module using te generic client setting:

https://www.drupal.org/docs/8/modules/openid-connect/client-configuration#toc-5

but need help to add a customized openid connect on nextcloud with social login app

thanks very much for help.

And github login works very well

**Comment by zorn-v** [comment]
Are you set scope to `openid` ?

**Comment by sealionking** [comment]
yes in one try I setit to openid

**Comment by edvanleeuwen** [comment]
I am having the same problem trying to tie Drupal and NC.

I have described it here: https://www.drupal.org/forum/support/post-installation/2019-07-31/set-up-oauth2-server-to-login-from-nextcloud

How can I test that the userinfo is retrieved properly?

**Comment by zorn-v** [comment]
> How can I test that the userinfo is retrieved properly?

`var_dump($userProfile, $data); die();` here https://github.com/zorn-v/nextcloud-social-login/blob/c69594d232945fe30ae386c3d75ef86f20713e3a/lib/Provider/CustomOpenIDConnect.php#L44
to check info from `id_token`

and 

`var_dump($profile); die();` here (before `if`) https://github.com/zorn-v/nextcloud-social-login/blob/c69594d232945fe30ae386c3d75ef86f20713e3a/lib/Provider/CustomOpenIDConnect.php#L53
to check response from userinfo endpoint

**Comment by edvanleeuwen** [comment]
Ok, I now see that information is passed between Drupal and NC. In NC the uid of Drupal is prefixed with 'drupal-' and this user is created.

How can I use the user name of Drupal to match a user name in NC?

**Comment by edvanleeuwen** [comment]
The first dump gives me the following:

`object(Hybridauth\User\Profile)#1040 (23) { ["identifier"]=> string(2) "48" ["webSiteURL"]=> NULL ["profileURL"]=> NULL ["photoURL"]=> NULL ["displayName"]=> NULL ["description"]=> NULL ["firstName"]=> NULL ["lastName"]=> NULL ["gender"]=> NULL ["language"]=> NULL ["age"]=> NULL ["birthDay"]=> NULL ["birthMonth"]=> NULL ["birthYear"]=> NULL ["email"]=> NULL ["emailVerified"]=> NULL ["phone"]=> NULL ["address"]=> NULL ["country"]=> NULL ["region"]=> NULL ["city"]=> NULL ["zip"]=> NULL ["data"]=> array(0) { } } object(Hybridauth\Data\Collection)#1039 (1) { ["collection":protected]=> object(stdClass)#1035 (6) { ["iss"]=> string(18) "https://mydrupal.com/" ["sub"]=> string(2) "48" ["aud"]=> string(9) "nextcloud" ["iat"]=> int(1564826696) ["exp"]=> int(1564830296) ["auth_time"]=> int(1564826696) } }`

The second:

`object(Hybridauth\Data\Collection)#1041 (1) { ["collection":protected]=> object(stdClass)#1043 (5) { ["sub"]=> NULL ["name"]=> string(13) "myusername" ["preferred_username"]=> string(13) "myusername" ["zoneinfo"]=> string(4) "3600" ["profile"]=> string(40) "https://mydrupal.com/gebruiker/mydrupaluser" } }`

Now I would like to use the user name to match the user in NC instead of 'drupal-48'.

**Comment by zorn-v** [comment]
> Now I would like to use the user name to match the user in NC instead of 'drupal-48'.

It's not possible due security reasons.

**Comment by edvanleeuwen** [comment]
So there is no way to map Drupal users to existing NC users? Because now, Drupal users are created in NC with a custom username 'drupal-XX'.

**Comment by zorn-v** [comment]
You can connect existing user to any social login. Just enable this setting and you can connect via personal settings of social login app.

**Comment by edvanleeuwen** [comment]
I am giving up. I think I lack the knowledge to tie these two together, it's taken me weeks and I have no progress . Thanks for your help though.

**Comment by edvanleeuwen** [comment]
For future reference: see https://www.drupal.org/forum/support/post-installation/2019-07-31/mapping-user-ids-via-oauth2-server-onto-nextcloud-users
