### ISSUE TITLE
[Facebook] The domain of this url isn't included in the app's domains.

### ISSUE THREAD

**Issue by jtagcat** [zorn-v/nextcloud-social-login#94]
Settings>User>Social login, pressing the Facebook button I get this:
![image](https://user-images.githubusercontent.com/38327267/59163203-49b52000-8aed-11e9-8532-7562e90853ee.png)

![image](https://user-images.githubusercontent.com/38327267/59163216-8123cc80-8aed-11e9-8399-9b9b3aa40568.png)
Blurred out domain is nextcloud's domain.

**Comment by kingwap99** [comment]
I have the same issue,
Can anyone help us?

**Comment by jonaszkadziela** [comment]
Hi everyone, I was facing the same issue. After a bit of tinkering, I found the root of the problem.

In my case, it turned out that SocialLogin was setting the 'redirect_uri' parameter to a URI with HTTP protocol instead of HTTPS, which is now required by Facebook.

I resolved this problem by adding the following line to the 'nextcloud/data/config/config.php' file:
`'overwriteprotocol' => 'https'`.

Here are my settings on 'facebook for developers' website (name, domain, ID and logo of the application have been changed for security reasons):

1. Basic settings
![Basic settings](https://user-images.githubusercontent.com/34022120/62212066-44af7700-b3a0-11e9-802c-944124a7aa1d.png)

2. Facebook Login settings
![Facebook Login settings](https://user-images.githubusercontent.com/34022120/62212113-66a8f980-b3a0-11e9-85f8-dc2683fa49de.png)
**Please note that 'Valid OAuth Redirect URIs' has no slash (/) at the end**

I hope this solution works for you as well.
If you have any questions, do not hesitate to contact me 😉

**Comment by zorn-v** [comment]
@jonaszkadziela thanks

**Comment by jtagcat** [comment]
Thanks, I even had that php setting, but I had facebook login not set up :)

**Comment by zorn-v** [comment]
Check the docs https://github.com/zorn-v/nextcloud-social-login/blob/master/docs/sso/facebook.md maybe it helps

**Comment by jtagcat** [comment]
Pardon, if I was unclear, I got it working!

**Comment by jtagcat** [comment]
Anyone googling: Snap: OAuth valid urls: `https://domain.tld/index.php/apps/sociallogin/oauth/facebook` (snap nextcloud has index.php in the url)
